### ISSUE TITLE
وصل نشدن به پروکسی از طریق pycharm

### ISSUE THREAD

**Issue by ParsaMirzaee** [bepass-org/oblivion-desktop#333]
### Attention | توجه

- [X] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

با تشکر از برنامه خوبتون
مشابه همین پیغام رو برای نرم افزار telegram گذاشتم که طبق کمکتون مشکلم برطرف شد
یه مشکل مشابه با نرم افزار pycharm داشتم که وقتی میخوام از پروکسی برای ارسال و دریافت اطلاعات استفاده کنم بهم این پیغام رو توی کنسول نشون میده.
Traceback (most recent call last):
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 123, in connect_tcp
    stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/parsa/PycharmProjects/pythonProject1/bot.py", line 125, in <module>
    app.run_polling(poll_interval=3)
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_application.py", line 871, in run_polling
    return self.__run(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_application.py", line 1069, in __run
    loop.run_until_complete(self.initialize())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_application.py", line 498, in initialize
    await self.bot.initialize()
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 299, in initialize
    await super().initialize()
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/_bot.py", line 772, in initialize
    await self.get_me()
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 1906, in get_me
    return await super().get_me(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/_bot.py", line 904, in get_me
    result = await self._post(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
  File "/Users/parsa/PycharmProjects/pythonProject1/.venv/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
تنظیمات System proxy فعال هست و توی pycharm هم از طریق Http proxy مشابه تلگرام بهش اطلاعات رو دادم ولی همچنان این پیغام رو میگیرم
سیستمم macbook m1 pro هست
با تشکر

### Relevant log output | لاگ برنامه

```shell
[2024-06-15 15:13:07.568] [info] past logs was deleted for new connection.
[2024-06-15 15:13:07.569] [info] ------------------------MetaData------------------------
[2024-06-15 15:13:07.570] [info] running on: darwin 23.5.0 arm64
[2024-06-15 15:13:07.570] [info] at od: 0.14.1-beta
[2024-06-15 15:13:07.570] [info] at wp: v1.2.3
[2024-06-15 15:13:07.570] [info] ls assets/bin: LICENSE,README.md,warp-plus
[2024-06-15 15:13:07.570] [info] method: gool
[2024-06-15 15:13:07.571] [info] proxyMode: true
[2024-06-15 15:13:07.571] [info] endpoint: default
[2024-06-15 15:13:07.571] [info] license: false
[2024-06-15 15:13:07.571] [info] exe: /Applications/Oblivion Desktop.app/Contents/MacOS/Oblivion Desktop
[2024-06-15 15:13:07.571] [info] userData: /Users/<USERNAME>/Library/Application Support/oblivion-desktop
[2024-06-15 15:13:07.572] [info] logs: /Users/<USERNAME>/Library/Logs/oblivion-desktop
[2024-06-15 15:13:07.572] [info] ------------------------MetaData------------------------
[2024-06-15 15:13:07.575] [info] starting wp process...
[2024-06-15 15:13:07.590] [info] /Users/<USERNAME>/Library/Application Support/oblivion-desktop/warp-plus --bind 127.0.0.1:8086 --gool --scan
[2024-06-15 15:13:07.594] [info] trying to set system proxy...
[2024-06-15 15:13:07.761] [info] Active Hardware Ports: Wi-Fi
[2024-06-15 15:13:07.761] [info] using hardwarePort: [ 'Wi-Fi' ]
[2024-06-15 15:13:07.761] [info] using hardwarePort: Wi-Fi
[2024-06-15 15:13:07.845] [info] Routing Rules: Customized
time=2024-06-15T15:13:07.897+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s

time=2024-06-15T15:13:07.898+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

[2024-06-15 15:13:08.019] [info] System proxy has been set for Wi-Fi.
time=2024-06-15T15:13:11.853+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.96.133 error="invalid handshake response length 16 bytes"

time=2024-06-15T15:13:13.402+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=2606:4700:d0:0:4d87:92c8:26c4:5a05 error="dial udp [2606:4700:d0:0:4d87:92c8:26c4:5a05]:5279: connect: no route to host"

time=2024-06-15T15:13:13.901+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.97.219:1843 RTT:164.674209ms CreatedAt:2024-06-15 15:13:13.401351 +0330 +0330 m=+5.508194626} {AddrPort:162.159.195.75:3476 RTT:239.412959ms CreatedAt:2024-06-15 15:13:10.502403 +0330 +0330 m=+2.609252084}]"
time=2024-06-15T15:13:13.901+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.97.219:1843 162.159.195.75:3476]"
time=2024-06-15T15:13:13.901+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-06-15T15:13:13.908+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-15T15:13:15.170+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.98.235 error="invalid handshake response length 16 bytes"

time=2024-06-15T15:13:18.780+03:30 level=INFO msg="connection test successful"

time=2024-06-15T15:13:18.784+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-06-15T15:13:19.985+03:30 level=INFO msg="connection test successful"
time=2024-06-15T15:13:19.985+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

time=2024-06-15T15:13:19.995+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=cp.cloudflare.com:80

time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:443

time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:80
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:80
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:5222
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:80
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.59:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=0.0.0.0:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.59:80
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=0.0.0.0:443
time=2024-06-15T15:13:20.301+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:443
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.53:443

time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=0.0.0.0:443
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.43:443
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:5222
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:80
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.91:5222
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.43:80
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.59:5222
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=192.124.55.6:443
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:443
time=2024-06-15T15:13:20.303+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.53:80

time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.41:5222
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.53:5222
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.43:5222
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=224.156.34.2:443

time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.50:80
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.223:443
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.50:5222

time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.223:80
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.223:5222
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.50:443
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=0.57.58.6:443
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.50:443
time=2024-06-15T15:13:20.304+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.50:80

time=2024-06-15T15:13:20.305+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.50:5222
time=2024-06-15T15:13:20.305+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=95.161.76.100:443
time=2024-06-15T15:13:20.305+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=95.161.76.100:5222
time=2024-06-15T15:13:20.305+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=95.161.76.100:80

time=2024-06-15T15:13:20.505+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56974: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.505+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56977: read: connection reset by peer" subsystem=vtun

time=2024-06-15T15:13:20.506+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56984: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.506+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56964: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.507+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56990: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.507+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56991: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.507+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56995: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.507+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56996: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.508+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56997: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.508+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56998: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.508+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56999: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.508+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:57000: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.509+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56976: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.509+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56978: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.510+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56980: read: connection reset by peer" subsystem=vtun
time=2024-06-15T15:13:20.510+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56993: read: connection reset by peer" subsystem=vtun

time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.53:443
time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.223:443

time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.151:443
time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.53:443
time=2024-06-15T15:13:21.234+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.43:443
time=2024-06-15T15:13:21.236+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443
time=2024-06-15T15:13:21.237+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443

time=2024-06-15T15:13:22.291+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=signaler-pa.clients6.google.com:443

time=2024-06-15T15:13:22.892+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=signaler-pa.clients6.google.com:443

time=2024-06-15T15:13:29.189+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=dns.google.com:443

time=2024-06-15T15:13:29.198+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=mozilla.cloudflare-dns.com:443

time=2024-06-15T15:13:30.238+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.151:443
time=2024-06-15T15:13:30.238+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443
time=2024-06-15T15:13:30.238+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.54:443
time=2024-06-15T15:13:30.238+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.151:443
time=2024-06-15T15:13:30.239+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:30.239+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:30.239+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:30.239+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.175.54:443
time=2024-06-15T15:13:30.239+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443

time=2024-06-15T15:13:35.157+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:56959: i/o timeout" subsystem=vtun

time=2024-06-15T15:13:38.879+03:30 level=WARN msg="read tcp 127.0.0.1:8086->127.0.0.1:57010: i/o timeout" subsystem=vtun

time=2024-06-15T15:13:39.090+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=signaler-pa.clients6.google.com:443

time=2024-06-15T15:13:39.336+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443
time=2024-06-15T15:13:39.337+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.167.92:443
time=2024-06-15T15:13:39.338+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=96.9.53.6:443
time=2024-06-15T15:13:39.338+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=149.154.165.96:443
time=2024-06-15T15:13:39.338+03:30 level=INFO msg="handling connection" subsystem=vtun protocol=tcp destination=32.92.49.6:443
```

**Comment by ircfspace** [comment]
سلام

ویژگی TUN درحال توسعه بوده و در آپدیت‌های بعدی در دسترس قرار میگیره
تا قبل از اون میتونین به کمک v2rayN یا نکوری مشکلتون رو برطرف کنین ([wiki](https://github.com/bepass-org/oblivion-desktop/wiki))
