### ISSUE TITLE
باگ  نصب  رویه لینوکس اوپن سوزه  با پکیچ  ان پی ام  

### ISSUE THREAD

**Issue by mohmmadView** [bepass-org/oblivion-desktop#87]
### Search first

- [X] I searched and no similar issues were found

## مشکل نصب در لینوکس  با ان پی ام  با ایرورر مواجه میشه به صورت کامل نصب نمیشه
سیستم و سیستم عامل استفاده شده

 node -v21.5.0 ; npm  v10.3.0 
=============================
Operating System: openSUSE Leap 15.4
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 6.5.9-lp154.6-default (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12400
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
======= ==================================
log :
```shell
> oblivion-desktop@0.2.44-beta postinstall
> ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && npm run build:dll
  • electron-builder  version=24.13.3
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/release/app
> oblivion-desktop@0.2.44-beta build:dll
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts
> oblivion-desktop@0.2.44-beta prepare
> ts-node script/dlWp.ts && husky
/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
script/dlWp.ts:4:19 - error TS7016: Could not find a declaration file for module 'axios'. '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/axios/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/axios` if it exists or add a new declaration (.d.ts) file containing `declare module 'axios';`

4 import axios from 'axios';
                    ~~~~~~~
script/dlWp.ts:12:34 - error TS7006: Parameter 'progressEvent' implicitly has an 'any' type.

12             onDownloadProgress: (progressEvent) => {
                                    ~~~~~~~~~~~~~
script/dlWp.ts:27:16 - error TS7006: Parameter 'response' implicitly has an 'any' type.

27         .then((response) => {
                  ~~~~~~~~
script/dlWp.ts:34:17 - error TS7006: Parameter 'error' implicitly has an 'any' type.

34         .catch((error) => {
                   ~~~~~

    at createTSError (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Object.require.extensions.<computed> [as .ts] (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  diagnosticCodes: [ 7016, 7006, 7006, 7006 ]
}
npm ERR! code 1
npm ERR! path /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta
npm ERR! command failed
npm ERR! command sh -c ts-node script/dlWp.ts && husky

``` 
با پکیچ yarn  به صورت کامل نصب شد اجرا شد با اضافه کردن  دستور yarn  کسای که مثل من تونستن با npm نصب کنن مشکلشون حل بشه ممنون از زحماتهای که کشیدن دوست عزیز با ارزوی موفقعیت اگه تو این راه احتیاج به کمک دارین و من اگر کمکی از دستم بربیاد خوشحال میشم با ارزوی موفقعیت

### Minimal Reproducible Example (MRE)

1- Extract oblivion-desktop-0.2.44-beta.tar.gz  
2- cd oblivion-desktop-0.2.44-beta.tar.gz
3- npm install
4- error TS7016 , error  TS7006 
npm ERR! code 1
npm ERR! path /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta 
npm ERR! command failed
npm ERR! command sh -c ts-node script/dlWp.ts && husky
5-not install npm 
6- test Jest log
```shell
Jest (oblivion-desktop-0.2.44-beta)

[info] Critical Settings:
jest.runMode: {
    "type": "watch"
}
jest.outputConfig: {
    "revealOn": "run",
    "revealWithFocus": "test-results",
    "clearOnRun": "none"
}
testing.openTesting: "openOnTestStart"


[info] auto config:

found:
  rootPath: /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta
  jestCommandLine: npm test --


> oblivion-desktop@0.2.44-beta test
> jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_oblivion_desktop_0_2_44_beta_1000.json --watch --no-coverage --reporters default --reporters /home/darksouls/.vscode/extensions/orta.vscode-jest-6.2.5/out/reporter.js --colors

jest-haste-map: Haste module naming collision: oblivion-desktop
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/release/app/package.json


--watch is not supported without git/hg, please use --watchAll

> Test run exited at 5/8/2024, 9:59:47 PM <


> oblivion-desktop@0.2.44-beta test
> jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_oblivion_desktop_0_2_44_beta_1000.json --watchAll --no-coverage --reporters default --reporters /home/darksouls/.vscode/extensions/orta.vscode-jest-6.2.5/out/reporter.js --colors


> Test run started at 5/8/2024, 9:59:48 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:18282) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 9:59:50 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.94 s
Ran all test suites.


> Test run started at 5/8/2024, 10:13:06 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:20810) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.224 s
Ran all test suites.

> Test run finished at 5/8/2024, 10:13:08 PM <



> Test run started at 5/8/2024, 10:13:10 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:20978) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 10:13:11 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.236 s
Ran all test suites.


> Test run started at 5/8/2024, 10:13:13 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:21150) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.269 s
Ran all test suites.

> Test run finished at 5/8/2024, 10:13:14 PM <



> Test run started at 5/8/2024, 10:21:42 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:27908) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 10:21:43 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.44 s
Ran all test suites.

node:internal/fs/watchers:255
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at NodeWatcher.watchdir (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/jest-haste-map/build/watchers/NodeWatcher.js:154:24)
    at /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/jest-haste-map/build/watchers/NodeWatcher.js:278:16
    at FSReqCallback.oncomplete (node:fs:202:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus',
  filename: '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus'
}

Node.js v21.5.0

[error] Jest process exited unexpectedly: Jest process "watch-all-tests" ended unexpectedly

[info] Open Quick Fix: → vscode-jest://oblivion-desktop-0.2.44-beta/io.orta.jest.with-workspace.show-quick-fix?%5B%22wizard%22%2C%22defer%22%2C%22disable-folder%22%2C%22help%22%5D

> Test run exited at 5/8/2024, 10:26:51 PM <


``` 

### Version

0.2.44-beta

### Platform/OS

Linux

### Relevant log output

```shell
Jest (oblivion-desktop-0.2.44-beta)

[info] Critical Settings:
jest.runMode: {
    "type": "watch"
}
jest.outputConfig: {
    "revealOn": "run",
    "revealWithFocus": "test-results",
    "clearOnRun": "none"
}
testing.openTesting: "openOnTestStart"


[info] auto config:

found:
  rootPath: /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta
  jestCommandLine: npm test --


> oblivion-desktop@0.2.44-beta test
> jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_oblivion_desktop_0_2_44_beta_1000.json --watch --no-coverage --reporters default --reporters /home/darksouls/.vscode/extensions/orta.vscode-jest-6.2.5/out/reporter.js --colors

jest-haste-map: Haste module naming collision: oblivion-desktop
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/release/app/package.json


--watch is not supported without git/hg, please use --watchAll

> Test run exited at 5/8/2024, 9:59:47 PM <


> oblivion-desktop@0.2.44-beta test
> jest --testLocationInResults --json --useStderr --outputFile /tmp/jest_runner_oblivion_desktop_0_2_44_beta_1000.json --watchAll --no-coverage --reporters default --reporters /home/darksouls/.vscode/extensions/orta.vscode-jest-6.2.5/out/reporter.js --colors


> Test run started at 5/8/2024, 9:59:48 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:18282) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 9:59:50 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.94 s
Ran all test suites.


> Test run started at 5/8/2024, 10:13:06 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:20810) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.224 s
Ran all test suites.

> Test run finished at 5/8/2024, 10:13:08 PM <



> Test run started at 5/8/2024, 10:13:10 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:20978) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 10:13:11 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.236 s
Ran all test suites.


> Test run started at 5/8/2024, 10:13:13 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:21150) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.269 s
Ran all test suites.

> Test run finished at 5/8/2024, 10:13:14 PM <



> Test run started at 5/8/2024, 10:21:42 PM <

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    The main process is not built yet. Build it by running "npm run build:main"

      12 |         chalk.whiteBright.bgRed.bold(
      13 |             'The main process is not built yet. Build it by running "npm run build:main"'
    > 14 |         )
         |          ^
      15 |     );
      16 | }
      17 |

      at Object.<anonymous> (.erb/scripts/check-build-exists.ts:14:11)

(node:27908) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> Test run finished at 5/8/2024, 10:21:43 PM <

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.44 s
Ran all test suites.

node:internal/fs/watchers:255
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at NodeWatcher.watchdir (/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/jest-haste-map/build/watchers/NodeWatcher.js:154:24)
    at /home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/jest-haste-map/build/watchers/NodeWatcher.js:278:16
    at FSReqCallback.oncomplete (node:fs:202:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus',
  filename: '/home/darksouls/Downloads/program/vpn/oblivion-vpn/oblivion-desktop-0.2.44-beta/node_modules/assert-plus'
}

Node.js v21.5.0

[error] Jest process exited unexpectedly: Jest process "watch-all-tests" ended unexpectedly

[info] Open Quick Fix: → vscode-jest://oblivion-desktop-0.2.44-beta/io.orta.jest.with-workspace.show-quick-fix?%5B%22wizard%22%2C%22defer%22%2C%22disable-folder%22%2C%22help%22%5D

> Test run exited at 5/8/2024, 10:26:51 PM <
```

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by kiomarzsss** [comment]
با درود و تشکر برای issue کاملی که ارسال کردید.
خطایی که دریافت کردید احتمالا داخل کامیت: ced7b1d683023d52fddea8420fa19245ce20a036 حل شده باشه.

خوشحال  و ممنون میشیم اگر بعد از انتشار نسخه بتا لینوکس از اون استفاده کنید و درصورت مواجه شدن با باگ بهمون اطلاع بدین 🙏🏽

**Comment by mohmmadView** [comment]
چشم حتما خوشحال میشم تو این کار کمکی بربیاد انجام بدهم با ارزوی موفقعیت
